Restore custom LdapResult rc for Abandon
We're not reporting an error for Abandon, because it's not an
error: it's been explicitly requested by the user. As a side
effect, the synchronous case is much nicer. It will be possible
to generate an error from a non-zero LdapResult rc, which will
cover terminate-futures-chain designs.